# Generated by Django 3.0 on 2020-04-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.IntegerField(default=0),
        ),
    ]
